apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: uservice-django-poc
  name: uservice-django-poc-api
  namespace: experiments
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: uservice-django-poc-api:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/dkharlan/uservice_django_poc.git
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: api.Dockerfile
      from:
        kind: ImageStreamTag
        name: python:3.6
        namespace: experiments 
    type: Source
  triggers:
  - github:
      secret: 1ccjwmdmV2qZnXFw_L-9
    type: GitHub
  - generic:
      secret: 9qt0AtwUOhWt_1kIIn83
    type: Generic
  - type: ConfigChange
  - imageChange:
    type: ImageChange

