apiVersion: v1
kind: ImageStream
metadata:
  labels:
    app: uservice-django-poc
  name: uservice-django-poc-frontend
  namespace: experiments
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: <...redacted...>/<...redacted...>/uservice-django-poc-frontend

