apiVersion: v1
kind: ImageStream
metadata:
  labels:
    app: uservice-django-poc
  name: httpd 
  namespace: experiments
spec:
  dockerImageRepository: "docker.io/httpd"
  lookupPolicy:
    local: false

